import { Download } from 'lucide-react';
import MainLayout from '../layout/MainLayout.jsx';
import Card from '../components/ui/Card.jsx';
import BarChart from '../components/charts/BarChart.jsx';
import DonutChart from '../components/charts/DonutChart.jsx';
import Table, { statusBadge } from '../components/ui/Table.jsx';

const rows=[{dept:'Khối Kỹ thuật',current:'420',new:'+12',quit:'-2',cost:'13,776,000,000 đ',status:'Hoàn tất'},{dept:'Phòng Kinh doanh',current:'350',new:'+25',quit:'-15',cost:'8,575,000,000 đ',status:'Hoàn tất'},{dept:'Hành chính Nhân sự',current:'65',new:'+3',quit:'-0',cost:'1,183,000,000 đ',status:'Chờ duyệt'},{dept:'Marketing',current:'112',new:'+8',quit:'-4',cost:'2,464,000,000 đ',status:'Hoàn tất'}];
export default function Reports(){return <MainLayout title="Báo cáo & Phân tích" subtitle="Theo dõi các chỉ số nhân sự và tài chính định kỳ"><div className="actions-row right"><select><option>Tháng này (11/2023)</option></select><select><option>Tổng hợp</option></select><button className="btn primary"><Download/> Xuất báo cáo</button></div><div className="grid reports-grid"><Card><h2>Phân bổ nhân sự</h2><div className="center"><DonutChart value={80} label="Tổng nhân sự"/></div><div className="report-lines"><p>Kỹ thuật <b>45%</b></p><p>Kinh doanh <b>35%</b></p><p>Khác <b>20%</b></p></div></Card><Card><h2>Tổng chi phí lương</h2><p>Tăng trưởng 12% so với tháng trước</p><BarChart values={[38,42,50,72,68,90]} /><div className="salary-boxes"><span>Kinh doanh <b>24,500,000 đ</b></span><span>Kỹ thuật <b>32,800,000 đ</b></span><span>Hành chính <b>18,200,000 đ</b></span></div></Card><Card><h2>Tỷ lệ nghỉ phép</h2>{[['Kỹ thuật',24],['Kinh doanh',58],['Hành chính & Nhân sự',12],['Marketing',35]].map(([n,w])=><div className="progress-row" key={n}><span>{n}<b>{w/10}%</b></span><div><i style={{width:`${w}%`}} /></div></div>)}</Card><Card><h2>Báo cáo cổ tức & Thưởng</h2><div className="stats-grid two"><div className="mini-stat">Tổng quỹ thưởng dự kiến<b>12.5 Tỷ VND</b></div><div className="mini-stat">Số lượng cổ phiếu ESOP<b>50,000 cp</b></div></div>{['Q1','Q2','Q3','Q4'].map((q,i)=><div className="progress-row" key={q}><span>{q}<b>{i<2?'Đã chi':i===2?'75%':'Kế hoạch'}</b></span><div><i style={{width:[100,100,75,0][i]+'%'}} /></div></div>)}</Card></div><Card><h2>Báo cáo biến động nhân sự tháng 11</h2><Table columns={[{key:'dept',label:'Phòng ban'},{key:'current',label:'Nhân sự hiện tại'},{key:'new',label:'Tuyển mới'},{key:'quit',label:'Nghỉ việc'},{key:'cost',label:'Chi phí lương'},{key:'status',label:'Trạng thái'}]} rows={rows} renderCell={(r,c)=>c.key==='status'?statusBadge(r.status):r[c.key]} /></Card></MainLayout>}
